# This file sets the theme for publishing this repo to github pages.

remote_theme: jekyll/slate

title: Pericardial fat GWAS colocalisation analysis

description: This repository explores colocalisations between a pericardial fat GWAS and tissue specific gene expressiom from GTEx8.